version: "3"

services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
     - "3000:3000"
    tty: true
    volumes:
     - ./server:/app
    networks: 
     - app-network
    environment:
      - MONGO_URI=mongodb://database/users
    depends_on:
      - database
    links:
      - database
    command: npm run start
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
     - "8080:8080"
    volumes: 
     - ./client:/app
    environment:
     - NODE_ENV=development
    depends_on: 
     - server
    command: npm run serve

volumes: 
  app_db_volume:
  mongodb_data_container:

networks: 
  app-network:
